language: cpp
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install g++-7 cmake libboost-test-dev libboost-program-options-dev doxygen graphviz -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
script:
  - gcc --version
  - g++ --version
  - cmake --version
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T matrix-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ualexandrbashkirev:$BINTRAY_API_KEY "https://api.bintray.com/content/alexandrbashkirev/otus_cpp/homeworks/$TRAVIS_BUILD_NUMBER/matrix-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
  
  - provider: pages
    local_dir: doc
    skip_cleanup: true
    github_token: $GITHUB_TOKEN 
    keep_history: true
    on:
      branch: master